name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  node_version: "14.x"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HEROKU_STAGING_APP_NAME: nestjs-starter-staging
  HEROKU_PRODUCTION_APP_NAME: nestjs-starter-production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  verify-docker-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: ./scripts/docker_setup_init.sh

      - name: Pull images
        run: docker-compose pull db

      - name: Docker build
        run: docker-compose build web

      - name: Docker init
        run: docker-compose run --rm web sh -c 'exit 0'

  build-and-upload-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      docker-tag: ${{ steps.meta.outputs.tags }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-upload-docker-image]
    env:
      NESTJS_STARTER_IMAGE: ${{ needs.build-and-upload-docker-image.outputs.docker-tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Init
      run: ./scripts/docker_setup_init.sh

    - name: Pull images
      run: docker-compose pull

    - name: Run lint
      run: docker-compose run web yarn lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-upload-docker-image]
    env:
      NESTJS_STARTER_IMAGE: ${{ needs.build-and-upload-docker-image.outputs.docker-tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Init
      run: ./scripts/docker_setup_init.sh

    - name: Pull images
      run: docker-compose pull

    - name: Run tests
      run: docker-compose run web yarn test

  test-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-upload-docker-image]
    env:
      NESTJS_STARTER_IMAGE: ${{ needs.build-and-upload-docker-image.outputs.docker-tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Init
      run: ./scripts/docker_setup_init.sh

    - name: Pull images
      run: docker-compose pull

    - name: Run request tests
      run: docker-compose run web yarn test:request

  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-upload-docker-image]
    env:
      NESTJS_STARTER_IMAGE: ${{ needs.build-and-upload-docker-image.outputs.docker-tag }}
      DUMMY_MOUNT: .:/dummy

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Init
      run: ./scripts/docker_setup_init.sh

    - name: Pull images
      run: docker-compose pull

    - name: Docker up
      run: docker-compose up --detach

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120

    - name: Save Cypress artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-artifacts
        path: |
          cypress/videos
          cypress/screenshots

    - name: Docker setup logs
      if: always()
      run: docker-compose logs --timestamps --tail="all" > docker-logs.txt

    - name: Save log artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: log-artifacts
        path: docker-logs.txt

  build-and-push-image-to-heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'thisismydesign'
    needs: [lint, test, test-request, test-e2e]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.heroku.com/${{ env.HEROKU_STAGING_APP_NAME }}/web,registry.heroku.com/${{ env.HEROKU_PRODUCTION_APP_NAME }}/web
          file: Dockerfile.prod
          cache-from: type=gha
          cache-to: type=gha

  deploy-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'thisismydesign'
    needs: [build-and-push-image-to-heroku]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Run release command
        run: heroku container:release web -a ${{ env.HEROKU_STAGING_APP_NAME }}

  test-e2e-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [deploy-staging]

    steps:
    - uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        wait-on: 'https://nestjs-starter-staging.herokuapp.com'
        wait-on-timeout: 120
        config-file: cypress.staging.config.ts

    - name: Save Cypress artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-artifacts-staging
        path: |
          cypress/videos
          cypress/screenshots

  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'thisismydesign'
    needs: [build-and-push-image-to-heroku, test-e2e-staging]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Run release command
        run: heroku container:release web -a ${{ env.HEROKU_PRODUCTION_APP_NAME }}

  test-e2e-production:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [deploy-production]

    steps:
    - uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        wait-on: 'https://nestjs-starter-production.herokuapp.com'
        wait-on-timeout: 120
        config-file: cypress.production.config.ts

    - name: Save Cypress artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-artifacts-production
        path: |
          cypress/videos
          cypress/screenshots
